{% set name = "apbs" %}
{% set version = "3.4.1" %}
{% set number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/Electrostatics/apbs/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 644e6246fd37c9dd4172fc7be1763337082ab8584dbcd53e738c831b62c89bb2
    
build:
    number: {{ number }}

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make
        - boost
        - swig
    host:
        - ncurses
        - bzip2
        - metis
        - openblas
        - pybind11
        - suitesparse
        - superlu

test:
    commands:
        - apbs --version || test $? -eq 13

about:
    home: http://www.poissonboltzmann.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.md
    summary: APBS solves the equations of continuum electrostatics for large biomolecular assemblages.
    doc_url: https://apbs.readthedocs.io/en/latest/
    dev_url: https://github.com/Electrostatics/apbs

extra:
  recipe-maintainers:
    - simonbray
    - bgruening
