travis:
  secure:
    BINSTAR_TOKEN: NX0+fNLbcZnE7Hig5rWw7pVKRZ/Mb1+QUEEeohUEdMTgyoxkMIfOQdMWkQvUJkcGEYKRj6eIh4Gj941Y1U1lbonStA1bOcLmlL47U0ooDx7tfBpac4DUMgtwd1KFgDQfmdGKsaF/Z4Q4EDaV70/0Z6qLeiZmzcUmcRDekb1znWuZlsVIELHD/2Rs4OheGg8kvzCnTitQcUn996KuMuXGC1Fbp6JQcPKjHZ0CZZtDUzWZ14Anz5WYR6DvAzLwilpHkir8UK2zIZOlXe0BQteipBhOsuZTpHawbYm315eeNzHRCgN0Rm5h1zhbuxqXbRogMbv7/xq4KOVi/qIoWNpZSTdGE1G2XsTMSdaxnevOBtNPbSz7o3xSQnu44u37JMXIjuuQLLTmFL5XGXgAmdh7aSEiXJ8rWhqvluCtYIIwK8SuYcrgXFgdsWpFkye2293kfm5vUfcoNE5NKazl49CWIXoZkjrtRO7bCYJSww440dU/dJ3c7q+EcFXOtBtk9llKyKt9gRHOuo+Y6CpWxlTEzO/KTpojmk5/LctW4UortATa6+djr9zErB8uLy02BzJKgnuFFqYHOWEHuHAGtK5e6AHXNUhsN4whDhjFxz2CIr37YuTQEMPeJOSxvhtjP4bXmSj5vfoSvwXLcljUb9MshCoDckYRk5GY2NVLgKfFmWw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
